
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: gebruderzulfaj-backk
    description: RESTful API.
    author: erblin zulfaj
    version: '@project.version@'
spring:
  profiles:
    active: dev